### ISSUE TITLE
Sem campo para mensagem

### ISSUE THREAD

**Issue by rafasoares1323** [l33one/livechat#2]
Olá,
Parabens pelo projeto, deu quase tudo certo aqui...
Mas quando eu clico no icone do Rocket chat no GLPI não aparece um campo para digitar a mensagem:
![image](https://user-images.githubusercontent.com/19491584/85740030-ab840000-b6d7-11ea-8f49-f257cc91ae73.png)

Sabe me informar se preciso configurar alguma coisa a mais?

**Comment by l33one** [comment]
Isso aconteceu comigo e era configuração do livechat no rocketchat.
Verificou o apontamento? IP e porta estão corretos? esta usando algun navegador que bloqueie scripts como Brave?

**Comment by dj-arezki** [comment]
HI 
I have a problem in my plugin livachat it is not working i don't know why 

![Capture d’écran du 2020-08-28 09-24-17](https://user-images.githubusercontent.com/8545916/91539038-9c584300-e910-11ea-9887-313e7cda6878.png)

and i have this message : Firefox cannot open this page

To protect your security, my server apache  will not allow Firefox to display the page if it is integrated by another site. To view this page, you must open it in a new window.

Find out more ...

Report similar errors to help Mozilla identify and block malicious sites

**Comment by dj-arezki** [comment]
Hi 
I just resolved the problem so i disable this # Restrict access inside any Iframe in menu administration -  general as like this 
![Capture d’écran du 2020-08-28 10-58-25](https://user-images.githubusercontent.com/8545916/91548543-6f5e5d00-e91d-11ea-8e0b-faac46028cdb.png)

so the problem it was in the server rocketchat ..finally not in my server appache 

best regards

**Comment by l33one** [comment]
> Hi
> I just resolved the problem so i disable this # Restrict access inside any Iframe in menu administration - general as like this
> ![Capture d’écran du 2020-08-28 10-58-25](https://user-images.githubusercontent.com/8545916/91548543-6f5e5d00-e91d-11ea-8e0b-faac46028cdb.png)
> 
> so the problem it was in the server rocketchat ..finally not in my server appache
> 
> best regards

Excelent, thank you for sharing the solution.
