### ISSUE TITLE
Incompatible con motor InnoDB.

### ISSUE THREAD

**Issue by aleadco** [l33one/livechat#3]
Las tablas creadas son incompatibles con el motor InnoDB,
Cuando se habilita en plugins se obtiene:
`Las tablas 1 no se migraron al motor InnoDB.`

**Comment by l33one** [comment]
Obrigado por reportar, vou verificar.

**Comment by aleadco** [comment]
Solution
`php /var/www/html/bin/console glpi:migration:myisam_to_innodb`
