### ISSUE TITLE
Compatibilização de versão

### ISSUE THREAD

**Issue by delson-filho** [l33one/livechat#4]
Boa tarde!

Poderia compatibilizar com a versão 9.5.0 ou superior?

Desde já agradeço! um excelente plugin!

**Comment by l33one** [comment]
Posso sim.

**Comment by paletitas** [comment]
Boa tarde. Estou com a mesma situação. Nas versões 9.5.1 e 9.5.2 ele também não funciona. Após instalar no GLPI e habilitar, nada mais acontece

Obrigado!

**Comment by l33one** [comment]
> Boa tarde. Estou com a mesma situação. Nas versões 9.5.1 e 9.5.2 ele também não funciona. Após instalar no GLPI e habilitar, nada mais acontece
> 
> Obrigado!

Este issue é para compatibilizar com a versão 9.5, para permitir instalar nesta versão. No seu caso, consegue instalar, mas nada acontece após a instalação. Se ainda continuar com o problema abre um novo issue, ok? 
abraço.

**Comment by l33one** [comment]
Compatibilizada com a versão 9.5.
